name: smartcam
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10

  # Đã xác nhận cài thành công
  - numpy=2.2.5
  - pillow=12.2.0
  - opencv=4.13.0
  - tqdm
  - onnxruntime

  # Cài insightface qua pip (không có trên conda)
  - pip:
    - insightface>=0.7.3
